<section class="row">                   
        <ul id="resources">
            <li class="progression"><?php echo $this->partial('/partials/new-promoters.phtml',[]) ?></li>
            
            <?php if(count($this->paginator) > 0): ?>
                <?php $count = 1 ; foreach ($this->paginator as $entityOnject): ?>
                    <li class="resource" id="resource_pet">
                        <div class="heading">
                        <h2>
                                      <a href="#!/pet" onclick="Docs.toggleEndpointListForResource('pet');"><?php echo $this->escape($count) ?></a>  : <?php echo $this->escape($entityOnject['name']) ?>
                        </h2>
                            <ul class="options">
                                <li>
                                  <a href="#!/pet" id="endpointListTogger_pet" onclick="Docs.toggleEndpointListForResource('pet');">Show/Hide</a>
                                </li>
                                <li>
                                  <a href="#" onclick="Docs.collapseOperationsForResource('pet'); return false;">
                                    List Operations
                                  </a>
                                </li>
                                <li>
                                  <a href="<?php echo $this->escape($this->url(array('module'=>'promoters','controller' => 'create', 'action' => 'delete' , 'id'=> $this->escape($entityOnject['id'])), null, true)) ?>" onclick="Docs.expandOperationsForResource('pet'); return false;">
                                    Remove
                                  </a>
                                </li>
                                <li>
                                  <a href="<?php echo $this->escape($this->url(array('module'=>'promoters','controller' => 'update', 'action' => 'index' , 'id'=> $this->escape($entityOnject['id'])), null, true)) ?>">Edit</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                <?php $count++; endforeach; ?>
            <?php else: ?>
                <li>  
                    <section class="row">
                        <div class="col-lg-12">
                            <p class="text-info info">
                                There are no promoters records in the BSSP system at the moment, please use the "create new promoter" link on the right to create records .
                            </p>
                        </div>
                    </section>
                </li>
            <?php endif; ?>              
            
            <li class="progression"><?php echo $this->partial('/partials/new-promoters.phtml',[]) ?></li>    
        </ul>   
</section>
<section>
    <?php echo $this->paginationControl($this->paginator, 'Elastic', ['partials/pagination.phtml' , 'service']); ?>
</section>