<form action="<?php echo $this->escape($this->form->getAction()) ?>" enctype="<?php echo $this->escape($this->form->getAttrib('enctype')) ?>" method="<?php echo $this->escape($this->form->getMethod()) ?>">
    
    <section class="contents">
    <div class="panel panel-primary">
          <div class="panel-heading">
          </div>
          <div class="panel-body">                   
            <div class="large-12 medium-12 columns">
<section id="tabs-wrap" class="tabs-wrap">
<ul class="tabs">
            <li id="tab1" class="current">Lot and Auction Details</li>
            <li id="tab2" class="">Items Details</li>
            <li id="tab3" class="">Buyer Details</li>
            <li id="tab4" class="">Payment</li>
</ul>
<div class="contents marginbot">
            <div class="tabscontent" id="content1" style="display: block;">
                <fieldset>
                    <ul>
                                <li><?php echo $this->form->lotId; ?></li>
                                <li><?php echo $this->form->lotCode; ?></li>
                                <li><?php echo $this->form->description; ?></li>
                                <li><?php echo $this->form->auctionId; ?></li>
                                
                                
                                <li id="auction-details"></li>
                    </ul>
                </fieldset>
            </div>

            <div class="tabscontent" id="content2" style="display: none;">
                        <fieldset>
                            <ul>
                                <li><?php echo $this->form->itemId; ?></li>
                                <li id="item-details"></li>
                            </ul>
                        </fieldset>        
            </div>
            <div class="tabscontent" id="content3" style="display: none;">
                        <fieldset>
                            <ul>
                                <li><?php echo $this->form->buyerId; ?></li>
                                <li id="buyer-details"></li>
                            </ul>
                        </fieldset>         
            </div>
            <div class="tabscontent" id="content4" style="display: none;">
                <fieldset>
                    <ul>
                        <li><?php echo $this->form->amount; ?></li>
                    </ul>
                </fieldset>        
            </div>    
</div>
</section>
            </div>
            <div class="large-12 medium-12 columns">
                <fieldset class="actions-wrap">
                    <ul id="actions">
                        <li><?php echo $this->form->btnSubmit; ?></li>
                        <li><?php echo $this->form->btnReset; ?></li>
                        <li><?php echo $this->form->btnCancel; ?></li>
                    </ul>
                </fieldset>                 
            </div>

            <div class="col-lg-12 text-right"></div> 
        </section>
</form> 