<form action="<?php echo $this->escape($this->form->getAction()) ?>" enctype="<?php echo $this->escape($this->form->getAttrib('enctype')) ?>" method="<?php echo $this->escape($this->form->getMethod()) ?>">

            <div class="frm-contents" id="content" >
                        <fieldset>
                            <section class="row">
                                <div class="col-lg-6"><?php echo $this->form->id; ?></div>
                            </section>
                        </fieldset>
                        <fieldset>
                            <legend>Budget Information</legend>
                            <section class="row">
                                <div class="col-lg-6"><?php echo $this->form->name; ?></div>
                                <div class="col-lg-4"><?php  ?></div>
                            </section>                           
                            <section class="row">
                                <div class="col-lg-4"><?php echo $this->form->period; ?></div>
                                <div class="col-lg-2"><?php echo $this->form->amount; ?></div>
                                <div class="col-lg-4"><?php  ?></div>
                            </section>
                            <section class="row">
                                <div class="col-lg-6"><?php echo $this->form->code; ?></div>
                                <div class="col-lg-6"><?php ?></div>
                            </section>                             
                            <section class="row">
                                <div class="col-lg-12"><?php echo $this->form->description; ?></div>
                            </section>                            
                           
                        </fieldset>                               
                <fieldset class="actions-wrap">
                    <ul id="actions">
                        <li><?php echo $this->form->btnSubmit->setLabel('Save Budget'); ?></li>
                        <li><?php echo $this->form->btnReset; ?></li>
                    </ul>
                </fieldset>
                </div> 

</form>    