<section class="row">
        <ul id="resources">
            <li class="progression"><?php echo $this->partial('/partials/new-extension.phtml',[]) ?></li>    
        </ul>
    
            <?php if(count($this->paginator) > 0): ?>
                <section class="">
                    <table>
                        <thead>
                            <tr>
                                <th>Project Number</th>
                                <th>Discussion Date</th>
                                <th>Extended To Date</th>
                                <th>Extension Phase</th>
                            </tr>            
                        </thead>
                        <tbody>
                            <?php $count = 1 ; foreach ($this->paginator as $entityOnject): ?>

                            <tr class="resource">
                                <td class="heading">
                                    <h2>
                                        <span class="text-muted"><?php echo $this->escape($count) ?></span>  : <?php echo $this->escape($entityOnject['projectNumber']) ?>
                                    </h2>                    
                                </td>
                                <td><?php echo $this->escape($entityOnject['discussionDate']) ?></td>
                                <td><?php echo $this->escape($entityOnject['extendedToDate']) ?></td>
                                <td><?php echo $this->escape($entityOnject['phase']) ?></td>
                                <td class="options text-right">
                                    <a href="<?php echo $this->escape($this->url(array('module'=>'extensions','controller' => 'create', 'action' => 'delete' , 'id'=> $this->escape($entityOnject['id'])), null, true)) ?>" onclick="Docs.expandOperationsForResource('pet'); return false;">
                                      Remove
                                    </a>
                                    <a href="<?php echo $this->escape($this->url(array('module'=>'extensions','controller' => 'update', 'action' => 'index' , 'id'=> $this->escape($entityOnject['id'])), null, true)) ?>">Edit</a>                   
                                </td>
                            </tr>

                    <?php $count++; endforeach; ?>
                        </tbody>
                    </table>
                </section>
            <?php else: ?>
                <section class="row">
                    <div class="col-lg-12">
                        <p class="text-info info">
                            There are no extensions records in the BSSP system at the moment, please use the "Create new assignment extension" link on the right to create records .
                        </p>
                    </div>
                </section>                            
            <?php endif; ?>      
        <ul id="resources">
            <li class="progression"><?php echo $this->partial('/partials/new-extension.phtml',[]) ?></li>    
        </ul>   
</section>
<section>
    <?php echo $this->paginationControl($this->paginator, 'Elastic', ['partials/pagination.phtml' , 'service']); ?>
</section>