<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        width:  600px;
        height: 400px;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        height: 100%;
    }
</style>

<section class="row">

    <section class="col-lg-6">
<div id="welcome">
    <div id="more-information">
        <p></p>
    </div>
</div>
    </section>
    <section class="col-lg-6">
        <?php
            if (!empty($this->message)) {
                    echo '<font color="red">';
                    echo $this->escape($this->message[0]);
                    echo '</font>';
            }

            $this->form->setName('login')
                       ->setAction('/index/login')
                       ->setMethod('post'); 
            echo $this->form; 
            ?>
    </section>
</section>