<?php echo $this->doctype(); ?>

<html lang="en" dir="ltr">
<head>
<?php echo $this->headTitle(); ?>
<?php echo $this->headMeta(); ///exit('default layout');?>
<link rel="stylesheet" href="<?php echo  $this->baseUrl('libs/jquery/ui/1.11/jquery-ui.min.css') ?>" type="text/css" media="all">
<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/style.css') ?>" type="text/css" media="all">
<!--    
<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/bootstrap.min.css') ?>" type="text/css" media="all">
<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/bootstrap-datepicker.css') ?>" type="text/css" media="all">
<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/bootstrap-dialog.css') ?>" type="text/css" media="all">

<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/font-awesome.min.css') ?>" type="text/css" media="all">

<link rel="stylesheet" href="<?php echo  $this->baseUrl('libs/jquery/ui/themes/base/minified/jquery-ui.min.css') ?>" type="text/css" media="all">

<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/style.css') ?>" type="text/css" media="all">
<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/ssc.css') ?>" type="text/css" media="all">
-->
<script src="<?php echo  $this->baseUrl('libs/jquery/2.1.1/jquery.min.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('libs/jquery/ui/1.11/jquery.ui.min.js'); ?>"></script>
<!--
<script src="<?php echo  $this->baseUrl('js/bootstrap.min.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('js/bootstrap-datepicker.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('js/bootstrap-dialog.js'); ?>"></script>

<script src="<?php echo  $this->baseUrl('libs/jquery/ui/1.10.3/minified/jquery.ui.datepicker.min.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('libs/jquery/tools/validate.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('js/setup.js'); ?>"></script>
 -->
<!--  Style -->
<script src="<?php echo  $this->baseUrl('js/sscfunctions.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('js/ssc.js'); ?>"></script>
<!-- .......... -->
<!--[if lt IE 9]>
<link rel="stylesheet" href="styles/ie.css" type="text/css" media="all">
<script src="scripts/ie/css3-mediaqueries.min.js"></script>
<script src="scripts/ie/ie9.js"></script>
<script src="scripts/ie/html5shiv.min.js"></script>
<![endif]-->
   <?php $this->headLink()
                          ->appendStylesheet($this->baseUrl('/css/natau.css'));?>
    <?php echo $this->navigation()->links(); ?>
   <?php echo $this->headLink(); ?>
   <?php echo $this->headScript(); ?>
<style>
    td{
        padding: 2px 4px;
    }
</style>
</head>
<body class="deedskiosk" onload="">
<div id="page">
<?php // echo $this->render('www-header.phtml'); ?>
<div id="menu" class="navbar navbar-default" role="navigation">
    <header class="container">
        <section class="row corporate">
            <div class="col-lg-5">
                <div id="logo">
                    <a class="navbar-brand" href="/"><img class="img" src="<?php echo $this->baseUrl('images/coart_of_arms.png'); ?>" alt="Namibia`s Coart of Arms" width="" height="" /></a>
                </div> 
                <h3>Government of Namibia</h3>
                <h4>Social Security Commission</h4>
                <h5>Web Portal</h5>
            </div>
            <div class="col-lg-7">
                <?php 
                echo $this->navigation()->menu()->setMinDepth(1)->setMaxDepth(1)->renderMenu(null , array(
                    'ulClass'=>'nav navbar-nav',
                    'liClass'=>'nav'
                )) . PHP_EOL;            
                ?>                 
            </div>            
            
        </section>
        <!--    <div class="navbar-header">
                <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>               
            </div>
            <div class="navbar-collapse collapse">
          
            </div> -->
    </header>

</div>
    <nav class="container">
        <section>
            <fieldset>
                
            
            <hgroup>
                <?php
                       // echo $this->navigation()->breadcrumbs() ->setSeparator("&nbsp; &frasl; &nbsp;")->setLinkLast(false)->setMinDepth(0)->render();
                ?>
            </hgroup>
            <hgroup>

            </hgroup>
                </fieldset>
        </section>
        <div class="page-header">
            <?php echo $this->partial('/partials/title.phtml',array('title'=>$this->title)) ?> 
        </div>              
    </nav>
<div id="body" class="container">
    <section class="row">
        <section class="col-md-12">
            <?php echo $this->flashMessages(); ?>
        </section>
        <section class="col-md-12">
                               <!-- Content -->
                        <?php echo $this->layout()->content; ?>
        </section>       
    </section>
</div>
    <div id="footer">
    <footer id="" class="container">
        <?php echo $this->render('footer.phtml'); ?>
    </footer>        
    </div>
</div>
</body>
</html>