<form action="<?php echo $this->escape($this->form->getAction()) ?>" enctype="<?php echo $this->escape($this->form->getAttrib('enctype')) ?>" method="<?php echo $this->escape($this->form->getMethod()) ?>">

            <div class="frm-contents" id="content" >
                        <fieldset>
                            <legend>Project Number</legend>                           
                            <section class="row text-info">
                                <div class="col-lg-6"><strong><?php echo $this->form->number->getValue(); ?></strong></div>
                                <div class="col-lg-3"><?php echo $this->form->number; ?></div>
                                <div class="col-lg-3"><?php echo $this->form->id; ?></div>
                            </section>                                                     
                        </fieldset>                 
                        <fieldset>
                            <legend>Application Information</legend>                           
                            <section class="row">
                                <div class="col-lg-6"><?php echo $this->form->applicationId; ?></div>
                            </section>                                                     
                        </fieldset>                
                        <fieldset>
                            <legend>Project Information</legend>
                            <section class="row">
                                <div class="col-lg-8"><?php echo $this->form->name; ?></div>
                                <div class="col-lg-4"><?php echo $this->form->status; ?></div>
                            </section>
                            <section class="row">
                                <div class="col-lg-12"><?php echo $this->form->tasks; ?></div>
                            </section>                            
                            <section class="row">
                                <div class="col-lg-12"><?php echo $this->form->description; ?></div>
                            </section>
                            <section class="row">
                                <div class="col-lg-3"><?php echo $this->form->startDate; ?></div>
                                <div class="col-lg-3"><?php echo $this->form->endDate; ?></div>
                                <div class="col-lg-6"></div>
                            </section>                             
                        </fieldset>                              
                <fieldset class="actions-wrap">
                    <ul id="actions">
                        <li><?php echo $this->form->btnSubmit; ?></li>
                        <li><?php echo $this->form->btnReset; ?></li>
                    </ul>
                </fieldset>
                </div> 

</form>    