
DROP TABLE IF EXISTS `city`;

CREATE TABLE `city` (
  `id` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(50) NOT NULL,
  `countryId` SMALLINT(5) UNSIGNED NOT NULL,
  `lastUpdate` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `createdBy` VARCHAR(24) DEFAULT NULL,
  `createdOn` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modifiedBy` VARCHAR(24) DEFAULT NULL,
  `modifiedOn` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_fk_country_id` (`countryId`),
  CONSTRAINT `fk_city_country` FOREIGN KEY (`countryId`) REFERENCES `country` (`id`) ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

/*Data for the table `city` */

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
