<form action="<?php echo $this->escape($this->form->getAction()) ?>" enctype="<?php echo $this->escape($this->form->getAttrib('enctype')) ?>" method="<?php echo $this->escape($this->form->getMethod()) ?>">

            <div class="frm-contents" id="content" >
                        <fieldset>
                            <legend>Project Information</legend>
                            <section class="row">
                                <div class="col-lg-6"><?php echo $this->form->projectNumber; ?></div>
                                <div class="col-lg-6"><?php ?></div>                                
                            </section>                                                      
                        </fieldset>                
                        <fieldset>
                            <legend>Extension Information</legend>
                            <section class="row">
                                <div class="col-lg-3"><?php echo $this->form->phase; ?></div>
                                <div class="col-lg-3"><?php echo $this->form->discussionDate; ?></div>
                                <div class="col-lg-3"><?php echo $this->form->extendedToDate; ?></div>
                            </section>
                            <section class="row">
                                <div class="col-lg-12"><?php echo $this->form->remarks; ?></div>
                            </section>                            
                        </fieldset>                              
                <fieldset class="actions-wrap">
                    <ul id="actions">
                        
                        <li><?php echo $this->form->btnMore->setLabel('Save and Create Another'); ?></li>
                        <li><?php echo $this->form->btnSubmit->setLabel('Save Extension'); ?></li>
                        <li><?php echo $this->form->btnReset; ?></li>
                    </ul>
                </fieldset>
                </div> 
</form>    