<section class="row">
    <div class="large-12 medium-12">
        <div class="panel panel-primary">
          <div class="panel-heading">
          </div>
          <div class="panel-body">                      
                <div class="large-12 medium-12 columns">
                    <div class="container" id="resources_container">
                        <section>
                            
                        </section>
                            
                        <ul class="">
                            <li>
                                <p><span class="fa fa-check"></span> <a href="<?php echo $this->escape($this->url(array('module' => 'auction','controller'=>'payments','action'=>'createdeposit'),null,true))?>">Make a new deposit</a></p>
                            </li>
                            <li>
                                <p><span class="fa fa-check"></span> <a href="<?php echo $this->escape($this->url(array('module' => 'auction','controller'=>'payments','action'=>'refunddeposit'),null,true))?>">Refund a buyer`s deposit</a></p>
                            </li>
                            <li>
                                <p><span class="fa fa-check"></span> <a href="<?php echo $this->escape($this->url(array('module' => 'auction','controller'=>'payments','action'=>'create'),null,true))?>">Make new payment</a></p>
                            </li>                           
                        </ul>

                    </div>
                </div>
              <div class="large-12 medium-12 columns text-right">              
              </div>              
        </div>
    </div>
    
</section>