<form action="<?php echo $this->escape($this->form->getAction()) ?>" enctype="<?php echo $this->escape($this->form->getAttrib('enctype')) ?>" method="<?php echo $this->escape($this->form->getMethod()) ?>">
    <section class="contents">
          <div class="panel-heading">
          </div>                    
            <div class="large-12 medium-12 columns">
<section id="tabs-wrap" class="tabs-wrap">
<ul class="tabs">
            <li id="tab1" class="current">Auction Details</li>
            <li id="tab2" class="">Buyer`s Details</li>
            <li id="tab3" class="">Deposit`s Details</li>
</ul>
<div class="contents marginbot">
            <div class="tabscontent" id="content1" style="display: block;">
                <fieldset>
                    <ul>
                        <li><?php echo $this->form->auctionName; ?></li>
                        <li><?php echo $this->form->auctionId; ?></li>
                    </ul>
                </fieldset>
            </div>

            <div class="tabscontent" id="content2" style="display: none;">
                        <fieldset>
                            <ul>
                                <li><?php echo $this->form->buyerName; ?></li>
                                <li><?php echo $this->form->buyerId; ?></li>
                            </ul>
                        </fieldset>        
            </div>

            <div class="tabscontent" id="content3" style="display: none;">
                        <fieldset>
                            <ul>
                                <li><?php echo $this->form->received; ?></li>
                                <li><?php echo $this->form->refunded; ?></li>
                                <li><?php echo $this->form->id; ?></li>
                            </ul>
                        </fieldset>         
            </div>   
</div>
</section>
            </div>
            <div class="large-12 medium-12 columns">
                <fieldset class="actions-wrap">
                    <ul id="actions">
                        <li><?php echo $this->form->btnSubmit; ?></li>
                        <li><?php echo $this->form->btnReset; ?></li>
                        <li><?php echo $this->form->btnCancel; ?></li>
                    </ul>
                </fieldset>                 
            </div>

            <div class="col-lg-12 text-right"></div> 
        </section>
</form>    